### ISSUE TITLE
Suggestion add option for remove from new tab

### ISSUE THREAD

**Issue by emrecanguldogan** [arnellebalane/simple-todo#111]
Instead of make a new tab, add functionality to settings so that if I select remove from homepage it will remove and when I click the symbol of extension open a pinned tab which I can access from there. I like search bar more in my new tabs so it really annoyed me if the extension purely written in JS I was going to change it myself but unfortunately svelte used, so I don't know how to do.

**Comment by arnellebalane** [comment]
This extension is also available as a web app at: https://simple-todo.arnelle.dev/
