### ISSUE TITLE
let the user add tags to any todo

### ISSUE THREAD

**Issue by hayat-tamboli** [arnellebalane/simple-todo#16]
## show todo like this 
![image](https://user-images.githubusercontent.com/55529269/118433240-22fbbd00-b6f8-11eb-83cb-0ae3cba7e1a7.png)

## tags can be added while making/editing a todo
![image](https://user-images.githubusercontent.com/55529269/118433322-5cccc380-b6f8-11eb-9dd4-b140325ffeff.png)

**This is how Notion lets me add tags**

**Comment by arnellebalane** [comment]
Implemented in #41
