### ISSUE TITLE
Add support for undo

### ISSUE THREAD

**Issue by charanjit-singh** [arnellebalane/simple-todo#20]
Add support for undoing the actions.

**Comment by arnellebalane** [comment]
@charanjit-singh Hey thanks for your feedback! 

There is already an undo for the following destructive actions:
- "Remove Done" button: turns into "Undo Remove" for a couple of seconds
- Deleting a todo: a toast component with an "Undo" button is shown at the bottom left corner for a couple of seconds

Which actions specifically would you like to add an undo for?
