### ISSUE TITLE
Frequently visited websites section.

### ISSUE THREAD

**Issue by shubhamscifi** [arnellebalane/simple-todo#50]
![image](https://user-images.githubusercontent.com/43269853/121812594-02d30580-cc86-11eb-89ef-95ac0375c049.png)

Please add a section showing frequently visited websites, as shown in the image.
#enhancement

**Comment by arnellebalane** [comment]
Implemented and will be released in [v1.12.0](https://github.com/arnellebalane/simple-todo/milestone/9)
