### ISSUE TITLE
Why does your extension require access to my browsing history?

### ISSUE THREAD

**Issue by jachinte** [arnellebalane/simple-todo#55]
Hi,

I was using your extension on Firefox when an update was triggered. It seems that your extension now requires access to my browsing history. Why is that?

Thank you.

**Comment by arnellebalane** [comment]
Hi! Thanks for the issue, the concern is definitely understandable.

The extension doesn't actually get your browser history. Browser extensions have an API that returns returns your frequently-visited sites (around 10-12 of them depending on the browser), that's all the extension gets. This additional permission is needed to implement this feature: #50 

![frequently-visited-light](https://user-images.githubusercontent.com/1428598/126665468-b7fadcd0-efc8-43d7-bf1f-f39c2153efc0.jpg)

Rest assured those frequently-visited sites are only used to display those links and remain on your browser (you can check the code too to make sure 😅 )

**Comment by jachinte** [comment]
Hi,

Thank you for clarifying that! I don't usually use this kind feature so I wasn't sure.

**Comment by arnellebalane** [comment]
Hi! Yeah, the permission needs to be requested even though you won't be using the feature, sorry for the confusion that it's caused! :pray:
