### ISSUE TITLE
Difficult to differentiate between same types of link

### ISSUE THREAD

**Issue by rishu541** [arnellebalane/simple-todo#57]
![image](https://user-images.githubusercontent.com/59786513/133283966-6fc31163-055c-4710-9581-6b5c3a5479eb.png)

**Comment by arnellebalane** [comment]
The icons here are obtained from the favicon of the site. Adding a way to customize the icons for each link would be too much work, and besides hovering on the icon shows a tooltip with the title of the page that it points to.

![image](https://user-images.githubusercontent.com/1428598/135541215-5f572da3-5410-4e33-a7c7-a0ae4825d2b7.png)

Closing this issue for now.
