### ISSUE TITLE
Tooltip is getting cut off

### ISSUE THREAD

**Issue by Daksh777** [arnellebalane/simple-todo#60]
The tooltip goes beyond the screen and gets cut offf
![image](https://user-images.githubusercontent.com/43648146/145679311-2c53bd19-95bd-4000-b94d-614b65e2482e.png)

**Comment by arnellebalane** [comment]
Implemented in #75, will be released in [`v1.13.0`](https://github.com/arnellebalane/simple-todo/milestone/8)
