### ISSUE TITLE
Unable to add website

### ISSUE THREAD

**Issue by Daksh777** [arnellebalane/simple-todo#62]
I'm unable to add https://www.adidas.co.in and it seems like the app is getting a 502
![image](https://user-images.githubusercontent.com/43648146/145679795-0430618e-a36d-4f7b-95c4-667fa124e602.png)

Is there any fix for this?

**Comment by arnellebalane** [comment]
I'm able to add https://www.adidas.co.in now. Not sure what happened actually, sorry :pray: Closing for now, will see if we encounter this again in the future.
