### ISSUE TITLE
Few options to make it complete

### ISSUE THREAD

**Issue by bhupesh-sf** [arnellebalane/simple-todo#63]
Hey, @arnellebalane  I installed your app as a chrome extension and I found it very useful though I look forward to a few more options that make it complete.

1. Recurrence + Due dates
2. Reminders
3. Filter (based on tags, separate lists etc)

But I must say this minimalistic idea of Todos really help to manage my day. Thanks for your good work.

Would like to know when are we planning to push new changes?

**Comment by arnellebalane** [comment]
Hi @bhupesh-sf , I'm glad that you found this useful 🎉  As for your requests,

- Recurrence: tracked in #31 
- Due dates: tracked in #38 
- Reminders: can you provide more info on what you had in mind about this feature?
- Filter: tracked in #47 

I'm currently still working on reorganizing the underlying extension code before proceeding to implement new features. I'm still about a week out on this. But the filters feature will be coming in the next release.

**Comment by bhupesh-sf** [comment]
Its amazing to hear from you. This extension is really cool from you and bringing the above mentioned features will surely make it forever tool in my toolkit.

Thanks for your good work.

**Comment by bhupesh-sf** [comment]
And regarding reminders, as I see in the Microsoft TODO web app, whenever a date/time comes it shows you a desktop notification. So in this way, I can plan my day with due times as well. And I will be reminded with a desktop notification whenever a due time to start/end for a task comes.

**Comment by arnellebalane** [comment]
I see, it's for desktop notifications. Thank you for clarifying. I've opened #68 to track this feature separately. I'll close this issue for now since the feature requests are now tracked in their individual issues. Thank you for all your inputs @bhupesh-sf ! 🙇
