### ISSUE TITLE
After build, some api's get a 404 error

### ISSUE THREAD

**Issue by shebaoting** [arnellebalane/simple-todo#64]
In dev state, everything is normal, such as the following two api, are normal
Open background
http://localhost:8888/.netlify/functions/get-background-image

Quick navigation
http://localhost:8888/.netlify/functions/get-quick-link-details?url=https:%2F%2Fwyz.xyz%2F

But after the build, the above two api's appear to be 404.
My guess is that the api route is not recognized.
I am using ngnix. how should I fix this error please?

This is the root of my site
![image](https://user-images.githubusercontent.com/29738814/150667271-0cb1eebe-07d2-484b-bdb6-8ddb7d057826.png)

**Comment by arnellebalane** [comment]
Hi @shebaoting , during development when running `npm run dev` we're using [Netlify CLI](https://docs.netlify.com/cli/get-started/) to run the the API functions locally. On build, the `SNOWPACK_PUBLIC_FUNCTIONS_URL` environment variable needs to be set to point to where the API functions are actually deployed.

The `/.netlify/functions/` APIs are only available when the functions are deployed to Netlify.
