### ISSUE TITLE
Does this project have to be deployed on top of netlify?

### ISSUE THREAD

**Issue by shebaoting** [arnellebalane/simple-todo#65]
Does this project have to be deployed on top of netlify?
I want to build it locally as a static site, can I?

**Comment by arnellebalane** [comment]
Hi @shebaoting , this project has two main components to it:
1. Frontend user interface
   - This is a static site, and can be deployed to any static-site hosting platforms (e.g. S3 + CloudFront, Firebase Hosting, etc.)
2. Backend functions (`functions` directory)
   - These functions provide additional server-side functionalities (e.g. getting background image information, etc.)
   - They are currently written to be deployed to Netlify Functions
   - They should theoretically also work when deployed to other functions-hosting services (e.g. Firebase Cloud Functions, AWS Lambda, etc.) but the functions code will need to be rewritten a bit to match the request handlers signatures that's expected by these other services. The function definitions themselves will likely stay the same

Once you managed to rewrite the functions and deploy to a different hosting service, you'll need to set this environment variable in the `.env` file to point to where you deployed them:
```
SNOWPACK_PUBLIC_FUNCTIONS_URL=
```
