### ISSUE TITLE
Add support for links

### ISSUE THREAD

**Issue by Daksh777** [arnellebalane/simple-todo#77]
It would be great if we could directly add hyperlinks to the list instead of treating links as normal text
![image](https://user-images.githubusercontent.com/43648146/152009591-693fd133-d229-4688-817a-3297b6fc26d6.png)

**Comment by arnellebalane** [comment]
Hi @Daksh777 , I'm planning to keep the todo text just plain text to keep it simple. However I've already considered supporting link attachments to the todos. They will most likely appear similar to the tags or other information besides the todo text. Will track this feature in #36 , so closing this for now. Thank you for your input! 🙇
