### ISSUE TITLE
About the box

### ISSUE THREAD

**Issue by bakinazik** [arnellebalane/simple-todo#84]
While adding a new to do, we should be able to close the box by clicking on the parts outside the box.

![photo](https://user-images.githubusercontent.com/64368231/153727825-3b890367-e7b6-413d-898d-4fe5d3395696.jpg)

**Comment by arnellebalane** [comment]
This is intentional, and designed to prevent the user from accidentally closing the popup while they are adding a todo. The popup can be closed by pressing the Escape key instead.
